# Generated by Django 3.0.2 on 2020-01-12 14:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2020, 1, 12, 14, 0, 0, 354826, tzinfo=utc))),
                ('shop', models.CharField(max_length=200, null=True)),
                ('client', models.CharField(max_length=200, null=True)),
                ('bonus_card', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(default=0, null=True)),
                ('worker', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
