# Generated by Django 3.0.2 on 2020-02-21 18:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analis', '0002_auto_20200112_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datestart', models.DateTimeField(default=django.utils.timezone.now)),
                ('datefinish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unique_clients_more_one', models.IntegerField()),
                ('favorite_shop', models.IntegerField()),
                ('favorite_shop_more_one', models.IntegerField()),
                ('other_shops_object', models.CharField(max_length=10000)),
                ('percent_object', models.CharField(max_length=10000)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analis.Report')),
            ],
        ),
    ]
