# Generated by Django 3.0.2 on 2020-02-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analis', '0003_report_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='unique_clients',
            field=models.IntegerField(default=0),
        ),
    ]
