# Generated by Django 3.0.2 on 2020-02-22 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analis', '0004_shop_unique_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=500)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('complete_date', models.DateTimeField(null=True)),
                ('parameters', models.CharField(max_length=1000)),
            ],
        ),
    ]
